import pandas as pd
import numpy as np
import joblib
import sys
import os
from src.features import create_features

def predict_on_new_data(csv_path, model_path="models/xgboost_model.pkl"):
    """
    Load a raw machine CSV, engineer features, and predict failure probabilities.
    """
    if not os.path.exists(csv_path):
        print(f"Error: Could not find file {csv_path}")
        return
        
    if not os.path.exists(model_path):
        print(f"Error: Could not find model at {model_path}. Please run python run_train.py first.")
        return

    print(f"Loading raw data from {csv_path}...")
    # 1. Load data
    df = pd.read_csv(csv_path)
    
    # Check if we have labels. If we do, we ignore them for prediction, 
    # but we might want to store them to evaluate later.
    if 'anomaly' in df.columns:
        df = df.drop(columns=['anomaly'])

    # 2. Feature Engineering
    print("Engineering time-series features...")
    # create_features automatically drops the dead sensors we defined in src/features.py
    df_features = create_features(df, machine_id_col=None) # No machine_id needed for a single file
    
    # 3. Clean up dataset for the model
    # Drop rows with NaNs (which are generated by the rolling windows at the very beginning of the timeline)
    # Actually, XGBoost handles NaNs, but we need to ensure inf values are replaced.
    df_features.replace([np.inf, -np.inf], np.nan, inplace=True)
    
    # Keep only the exact features the model was trained on
    # (Excluding machine_id, early_warning, anomaly which aren't in X_train)
    cols_to_drop = [c for c in ['machine_id', 'anomaly', 'early_warning'] if c in df_features.columns]
    X_inference = df_features.drop(columns=cols_to_drop)

    # 4. Load Model
    print(f"Loading trained XGBoost model from {model_path}...")
    model = joblib.load(model_path)
    
    # 5. Make Predictions
    print("Generating predictions...")
    probabilities = model.predict_proba(X_inference)[:, 1]
    
    # Using the optimized threshold from our training log (0.10)
    threshold = 0.10
    predictions = (probabilities >= threshold).astype(int)
    
    # Add predictions back to the original dataframe
    df['failure_probability'] = probabilities
    df['predicted_warning'] = predictions
    
    # Show summary
    total_warnings = predictions.sum()
    print("\n--- Prediction Summary ---")
    print(f"Total time steps analyzed: {len(df)}")
    print(f"Time steps flagged as 'Danger Zone': {total_warnings}")
    
    if total_warnings > 0:
        first_warning_idx = df.index[df['predicted_warning'] == 1].tolist()[0]
        print(f"FIRST WARNING flagged at time step: {first_warning_idx}")
        print(f"Probability at first warning: {probabilities[first_warning_idx]:.2f}")
    else:
        print("Machine appears healthy! No warnings generated.")

    # Save output
    output_path = csv_path.replace(".csv", "_predictions.csv")
    df.to_csv(output_path, index=False)
    print(f"\nSaved detailed predictions to {output_path}")

if __name__ == "__main__":
    # Test on a specific machine
    test_file = "Data/processed/test/machine-1-1.csv"
    predict_on_new_data(test_file)
